[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pwa-tools"
version = "0.1" # Reminder to update this version number as needed.
description = "Hydro conditioning tools for PWA workflows"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["pwa_tools"]